# Generated by Django 4.2.12 on 2025-05-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_principal', '0010_aluno_aprovado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_principal.aluno', verbose_name='Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_principal.professor', verbose_name='Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_principal.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
            },
        ),
    ]
