# Generated by Django 4.2.12 on 2025-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0010_aluno_aprovado'),
        ('area_aluno', '0002_remove_frequenciaaluno_aluno_frequenciaaluno_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciaaluno',
            name='alunos',
            field=models.ManyToManyField(to='area_principal.aluno', verbose_name='Alunos'),
        ),
    ]
