# Generated by Django 4.2.12 on 2025-05-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0013_responsavel_cpf_responsavel_parentesco_and_more'),
        ('area_aluno', '0003_alter_frequenciaaluno_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciaaluno',
            name='alunos_faltas_abonadas',
            field=models.ManyToManyField(blank=True, related_name='alunos_faltas_abonadas', to='area_principal.aluno', verbose_name='Alunos que justificaram a falta'),
        ),
    ]
