# Generated by Django 4.2.12 on 2025-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0002_disciplina_turma_responsavel_professor_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matricula'),
        ),
    ]
