# Generated by Django 4.2.12 on 2025-05-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0003_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='responsaveis',
            field=models.ManyToManyField(limit_choices_to={'responsavel__tipo': 'Responsavel'}, to='area_principal.responsavel', verbose_name='Responsáveis'),
        ),
    ]
