# Generated by Django 4.2.12 on 2025-05-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0004_alter_aluno_responsaveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='responsaveis',
            field=models.ManyToManyField(to='area_principal.responsavel', verbose_name='Responsáveis'),
        ),
    ]
