# Generated by Django 4.2.12 on 2025-05-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0005_alter_aluno_responsaveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
