# Generated by Django 4.2.12 on 2025-05-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0006_turma_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area_principal.disciplina', verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area_principal.professor', verbose_name='Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area_principal.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(max_length=10, verbose_name='Nota')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area_principal.aluno', verbose_name='Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area_principal.professor', verbose_name='Professor')),
                ('prova_feita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area_principal.prova', verbose_name='Prova feita pelo aluno')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
