# Generated by Django 4.2.12 on 2025-05-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0007_prova_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='data',
            field=models.DateField(verbose_name='Data de aplicação'),
        ),
    ]
