# Generated by Django 4.2.12 on 2025-05-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0008_alter_prova_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='area_principal.disciplina', verbose_name='Disciplinas da turma'),
        ),
    ]
