# Generated by Django 4.2.12 on 2025-05-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0009_turma_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='aprovado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aprovado'),
        ),
    ]
