# Generated by Django 4.2.12 on 2025-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0010_aluno_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='bimestre',
            field=models.CharField(blank=True, choices=[('1° Bimestre', '1° Bimestre'), ('2° Bimestre', '2° Bimestre'), ('3° Bimestre', '3° Bimestre'), ('4° Bimestre', '4° Bimestre')], max_length=20, null=True, verbose_name='Bimestre'),
        ),
    ]
