# Generated by Django 4.2.12 on 2025-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0011_prova_bimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='concursado',
            field=models.BooleanField(default=False, verbose_name='Concursado'),
        ),
        migrations.AddField(
            model_name='professor',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário'),
        ),
    ]
