# Generated by Django 4.2.12 on 2025-05-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_principal', '0012_professor_concursado_professor_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(blank=True, help_text='Ex: 123.456.789-10', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Responsável', 'Responsável')], null=True, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
